db:
  image: dockerfile/mongodb
  ports:
  - "27017"  

app:
  build: .
  environment:
    NODE_ENV: production
    PORT: 80
    SERVICE_NAME: app
  links:
  - "db:DB"
  ports:
  - "80"

lb:
  image: jasonwyatt/nginx-loadbalancer
  links:
  - app
  environment:
    APP_PATH: "/"
  ports:
  - "80:80"